<?php

/**
 * @file
 * Contains acquia_pendo.module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function acquia_pendo_preprocess_html(&$variables) {
  // Overwrite the Pendo API key with the one provided by Acquia.
  if (getenv('AH_PENDO_KEY') !== FALSE) {
    $variables['#attached']['drupalSettings']['pendo']['api_key'] = getenv('AH_PENDO_KEY');
  }

  $acquia_env_vars = [
    'AH_CURRENT_REGION',
    'AH_SITE_NAME',
    'AH_APPLICATION_UUID',
    'AH_REALM',
    'AH_NON_PRODUCTION',
    'AH_SITE_ENVIRONMENT',
    'AH_SITE_GROUP',
  ];
  foreach ($acquia_env_vars as $value) {
    if (getenv($value) !== FALSE) {
      $variables['#attached']['drupalSettings']['pendo']['data']['account'][$value] = getenv($value);
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function acquia_pendo_form_pendo_admin_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  if ($ahPendoApiKey = getenv('AH_PENDO_KEY')) {
    $form['api_key']['#disabled'] = TRUE;
    $form['api_key']['#prefix'] = t('This application is being run in an Acquia environment. The Acquia Pendo API key will be used automatically.');
    $form['api_key']['#value'] = $ahPendoApiKey;
    $form['actions']['submit']['#disabled'] = TRUE;
  }
}
